import {React,useState} from 'react';
import {useNavigate} from'react-router-dom';

import {preview} from '../assets';
import {FormField,Loader} from '../components';
import {getRandomPrompt} from '../utils';

const CreatePost = () => {
  const navigate=useNavigate();
  const [form,setForm]=useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingImg,setgeneratingImg]=useState(false);
  const [loading,setLoading]=useState(false);

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
      <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px] '>Create stunnig images generated by AI</p> 
      </div>      
    </section>
  )

}
